{{- if .Values.namespace -}}
{{/*
  命名空间
*/}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "app.namespace" . | quote }}
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
{{- end }}
