{{/*
  Secret — 密码和密钥
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secrets
  namespace: {{ include "app.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.auth.rootPassword | default "change-me-in-production" | quote }}

  SPRING_DATASOURCE-CONFIG_USERNAME: {{ .Values.app.externalDatabase.username | default "root" | quote }}
  SPRING_DATASOURCE-LOG_USERNAME:     {{ .Values.app.externalDatabase.username | default "root" | quote }}
  SPRING_DATASOURCE-TOKEN_USERNAME:   {{ .Values.app.externalDatabase.username | default "root" | quote }}
  SPRING_DATASOURCE-CONFIG_PASSWORD: {{ .Values.mysql.auth.rootPassword | default "change-me-in-production" | quote }}
  SPRING_DATASOURCE-LOG_PASSWORD:     {{ .Values.mysql.auth.rootPassword | default "change-me-in-production" | quote }}
  SPRING_DATASOURCE-TOKEN_PASSWORD:   {{ .Values.mysql.auth.rootPassword | default "change-me-in-production" | quote }}

  SPRING_DATA_REDIS_PASSWORD: {{ .Values.redis.auth.password | default "change-me-redis" | quote }}
